### ISSUE TITLE
Is this what used to be Radi-HTTP.js?

### ISSUE THREAD

**Issue by rafaelklaessen** [Marcisbee/radi-fetch#1]

**Comment by Marcisbee** [comment]
That is correct !

**Comment by jpitchardu** [comment]
So my guess is that it will use the `fetch` api instead of `XmlHttpRequest` as it was before.

Is this repo the one that's referenced in the (project)[https://github.com/radi-js/radi/projects/1] on the In progress column?

**Comment by Marcisbee** [comment]
@pichardoJ Currently plan is to write it in `XmlHttpRequest` as the code footprint is so tiny and there are few benefits, like that it works on any browser (as I work for startups and projects that tend to be addressed for use in schools and lot's of them still use IE). But will switch to fetch api when the time comes.

Yes, that is the one.

**Comment by jpitchardu** [comment]
Oh ok, is there anyway we could contribute? Any codebase?

**Comment by rafaelklaessen** [comment]
The original source code can be found here, I believe: [radi-js/radi/blob/master/src/radi-http.js](https://github.com/radi-js/radi/blob/master/src/radi-http.js)

**Comment by Marcisbee** [comment]
That is the one. On this weekend I will finish to make some changes and publish code in this `radi-fetch` repo.

The idea of radi-fetch is to eventually make automatic loading state changes. So in component we could just do this:

```jsx
{ this.$http.waiting ? 'Loading..' : <div>Done</div> }
```

```jsx
{ this.$http.waiting.for('/user/.*') ? <LoadingPlaceholder /> : <div>Done</div> }
```

Without doing `this.loading = true` and `this.loading = false` every time. Also appending loading flags to DOM nodes for CSS to automatically style something when loading is happening.

**Comment by jpitchardu** [comment]
All right it looks like a good idea, I'll standby then.
